# Generated by Django 4.2.3 on 2023-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='subject',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
